USE QL_MAYLANH_HQTCSDL 

--Đừng chạy default

--Ràng buộc CHECK
--1
ALTER TABLE SANPHAM
ADD CONSTRAINT CHK_SANPHAM_SOLUONG CHECK (SOLUONG >= 0);

--2
ALTER TABLE HOADONNHAP
ADD CONSTRAINT CHK_HOADONNHAP_NGAYNHAP CHECK (NGAYNHAP <= GETDATE());

--3
ALTER TABLE HOADONXUAT
ADD CONSTRAINT CHK_HOADONXUAT_NGAY CHECK (NGAY <= GETDATE());

--4
ALTER TABLE CTHOADONNHAP
ADD CONSTRAINT CHK_CTHOADONNHAP_SOLUONG CHECK (SOLUONG >= 1);

--5
ALTER TABLE CHITIETHOADONXUAT
ADD CONSTRAINT CHK_CHITIETHOADONXUAT_SOLUONG CHECK (SOLUONG >= 1);

--Ràng buộc UNIQUE
--1
ALTER TABLE SANPHAM
ADD CONSTRAINT UQ_SANPHAM_TENSANPHAM UNIQUE (TENSANPHAM);

--2
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT UQ_NHACUNGCAP_TENNCC UNIQUE (TENNCC);

--3
ALTER TABLE KHACHHANG
ADD CONSTRAINT UQ_KHACHHANG_SODIENTHOAI UNIQUE (SODIENTHOAI);

--4
ALTER TABLE NHANVIEN
ADD CONSTRAINT UQ_NHANVIEN_SODIENTHOAI UNIQUE (SODIENTHOAI);

--5
ALTER TABLE NGUOIDUNG
ADD CONSTRAINT UQ_NGUOIDUNG_USERNAME UNIQUE (USERNAME);

--Ràng buộc DEFAULT
--1
ALTER TABLE NHACUNGCAP
ADD CONSTRAINT DF_NHACUNGCAP_DIACHI DEFAULT N'Chưa cập nhật' FOR DIACHI;

--2
ALTER TABLE KHACHHANG
ADD CONSTRAINT DF_KHACHHANG_DIACHI DEFAULT N'Chưa cập nhật' FOR DIACHI;

--3
ALTER TABLE NHANVIEN
ADD CONSTRAINT DF_NHANVIEN_DIACHI DEFAULT N'Chưa cập nhật' FOR DIACHI;

--4
ALTER TABLE THONGKE
ADD CONSTRAINT DF_THONGKE_NGAY DEFAULT GETDATE() FOR NGAY;