USE QL_MAYLANH_HQTCSDL 

--DASHBOARD
--1: Đếm số lượng Nhân viên kho hàng:
GO
CREATE PROCEDURE NVKH_CountEmployees
AS
BEGIN
    SELECT COUNT(*) AS EmployeeCount FROM NGUOIDUNG WHERE MAQUYEN = 'Q3';
END;

EXEC NVKH_CountEmployees;


--HOA DON NHAP
--1: Thêm hóa đơn nhập và chi tiết hóa đơn nhập
GO
CREATE PROCEDURE NVKH_AddHoaDonNhap
    @MAHDN VARCHAR(10),
    @MANV VARCHAR(10),
    @MANCC VARCHAR(10),
    @NGAYNHAP DATE,
    @TONGTIEN DECIMAL(18, 0)
AS
BEGIN
    INSERT INTO HOADONNHAP (MAHDN, MANV, MANCC, TONGTIEN, NGAYNHAP)
    VALUES (@MAHDN, @MANV, @MANCC, @TONGTIEN, @NGAYNHAP);
END;
GO

CREATE PROCEDURE NVKH_AddCTHoaDonNhap
    @MACTHDN VARCHAR(10),
    @MAHDN VARCHAR(10),
    @MASANPHAM VARCHAR(10),
    @SOLUONG INT,
    @DONGIA DECIMAL(18, 0)
AS
BEGIN
    INSERT INTO CTHOADONNHAP (MACTHDN, MAHDN, MASANPHAM, SOLUONG, DONGIA)
    VALUES (@MACTHDN, @MAHDN, @MASANPHAM, @SOLUONG, @DONGIA);
END;
GO

--2: Xóa hóa đơn nhập và chi tiết hóa đơn nhập
GO
CREATE PROCEDURE NVKH_DeleteHoaDonNhap
    @MAHDN VARCHAR(10)
AS
BEGIN
    -- Xóa chi tiết hóa đơn nhập trước
    DELETE FROM CTHOADONNHAP WHERE MAHDN = @MAHDN;

    -- Xóa hóa đơn nhập
    DELETE FROM HOADONNHAP WHERE MAHDN = @MAHDN;
END;
GO

--3: Cập nhật hóa đơn nhập và chi tiết hóa đơn nhập
GO
CREATE PROCEDURE NVKH_UpdateHoaDonNhap
    @MAHDN VARCHAR(10),
    @MANV VARCHAR(10),
    @MANCC VARCHAR(10),
    @NGAYNHAP DATE,
    @TONGTIEN DECIMAL(18, 0)
AS
BEGIN
    UPDATE HOADONNHAP
    SET MANV = @MANV, MANCC = @MANCC, TONGTIEN = @TONGTIEN, NGAYNHAP = @NGAYNHAP
    WHERE MAHDN = @MAHDN;
END;
GO

CREATE PROCEDURE NVKH_UpdateCTHoaDonNhap
    @MAHDN VARCHAR(10),
    @MASANPHAM VARCHAR(10),
    @SOLUONG INT,
    @DONGIA DECIMAL(18, 0)
AS
BEGIN
    UPDATE CTHOADONNHAP
    SET MASANPHAM = @MASANPHAM, SOLUONG = @SOLUONG, DONGIA = @DONGIA
    WHERE MAHDN = @MAHDN;
END;
GO

--4: Tìm kiếm hóa đơn nhập
GO
CREATE PROCEDURE NVKH_SearchHoaDonNhap
    @MAHDN VARCHAR(10)
AS
BEGIN
    SELECT HDN.MAHDN, NV.MANV, NV.TENNV, NCC.MANCC, NCC.TENNCC, HDN.NGAYNHAP, HDN.TONGTIEN, 
           CTHDN.MASANPHAM, SP.TENSANPHAM, CTHDN.SOLUONG, CTHDN.DONGIA
    FROM HOADONNHAP HDN
    INNER JOIN NHANVIEN NV ON HDN.MANV = NV.MANV
    INNER JOIN NHACUNGCAP NCC ON HDN.MANCC = NCC.MANCC
    INNER JOIN CTHOADONNHAP CTHDN ON HDN.MAHDN = CTHDN.MAHDN
    INNER JOIN SANPHAM SP ON CTHDN.MASANPHAM = SP.MASANPHAM
    WHERE HDN.MAHDN LIKE '%' + @MAHDN + '%';
END;
GO

--5: Lấy danh sách tất cả các nhân viên
GO
CREATE PROCEDURE NVKH_GetAllNhanVien
AS
BEGIN
    SELECT * FROM NHANVIEN;
END;
GO

--6: DataGridView
GO
CREATE PROCEDURE NVKH_GetAllHoaDonNhap
AS
BEGIN
    SELECT HDN.MAHDN, NV.MANV, NV.TENNV, NCC.MANCC, NCC.TENNCC, HDN.NGAYNHAP, HDN.TONGTIEN, 
           CTHDN.MASANPHAM, SP.TENSANPHAM, CTHDN.SOLUONG, CTHDN.DONGIA
    FROM HOADONNHAP HDN
    INNER JOIN NHANVIEN NV ON HDN.MANV = NV.MANV
    INNER JOIN NHACUNGCAP NCC ON HDN.MANCC = NCC.MANCC
    INNER JOIN CTHOADONNHAP CTHDN ON HDN.MAHDN = CTHDN.MAHDN
    INNER JOIN SANPHAM SP ON CTHDN.MASANPHAM = SP.MASANPHAM;
END;
GO

--7: Kiểm tra xem mã hóa đơn nhập có tồn tại trong cơ sở dữ liệu hay không
GO
CREATE PROCEDURE NVKH_CheckHoaDonNhapExists
    @MAHDN VARCHAR(10)
AS
BEGIN
    SELECT COUNT(*) FROM HOADONNHAP WHERE MAHDN = @MAHDN;
END;
GO

--8: Lấy đơn giá nhập theo sản phẩm tương ứng
CREATE PROCEDURE NVKH_LayDonGiaNhapTheoSP
    @MaSP  NVARCHAR(255)
AS
BEGIN
    SELECT DONGIANHAP 
    FROM SANPHAM 
    WHERE MASANPHAM = @MaSP
END;



--HOA DON XUAT
--1: Lấy danh sách tất cả các khách hàng
GO
CREATE PROCEDURE NVKH_GetAllKhachHang
AS
BEGIN
    SELECT * FROM KHACHHANG;
END;

--2: DataGridView
GO
CREATE PROCEDURE NVKH_GetAllHoaDonXuat
AS
BEGIN
    SELECT HDX.MAHDX, NV.MANV, NV.TENNV, KH.MAKH, KH.TENKH, HDX.NGAY, HDX.TONGTIEN, 
           CTHDX.MASANPHAM, SP.TENSANPHAM, CTHDX.SOLUONG, CTHDX.DONGIA
    FROM HOADONXUAT HDX
    INNER JOIN NHANVIEN NV ON HDX.MANV = NV.MANV
    INNER JOIN KHACHHANG KH ON HDX.MAKH = KH.MAKH
    INNER JOIN CHITIETHOADONXUAT CTHDX ON HDX.MAHDX = CTHDX.MAHDX
    INNER JOIN SANPHAM SP ON CTHDX.MASANPHAM = SP.MASANPHAM;
END;
GO

--3: Thêm hóa đơn xuất và chi tiết hóa đơn xuất
GO
CREATE PROCEDURE NVKH_AddHoaDonXuat
    @MAHDX VARCHAR(20),
    @MAKH VARCHAR(20),
    @MANV VARCHAR(20),
    @TONGTIEN DECIMAL(18, 2),
    @NGAY DATETIME
AS
BEGIN
    INSERT INTO HOADONXUAT (MAHDX, MAKH, MANV, TONGTIEN, NGAY)
    VALUES (@MAHDX, @MAKH, @MANV, @TONGTIEN, @NGAY);
END;
GO

GO
CREATE PROCEDURE NVKH_AddChiTietHoaDonXuat
    @MACTHDX VARCHAR(20),
    @MAHDX VARCHAR(20),
    @MASANPHAM VARCHAR(20),
    @SOLUONG INT,
    @DONGIA DECIMAL(18, 2)
AS
BEGIN
    INSERT INTO CHITIETHOADONXUAT (MACTHDX, MAHDX, MASANPHAM, SOLUONG, DONGIA)
    VALUES (@MACTHDX, @MAHDX, @MASANPHAM, @SOLUONG, @DONGIA);
END;
GO

--4: Xóa hóa đơn xuất và chi tiết hóa đơn xuất
GO
CREATE PROCEDURE NVKH_DeleteHoaDonXuat
    @MAHDX VARCHAR(20)
AS
BEGIN
        -- Xóa chi tiết hóa đơn xuất
        DELETE FROM CHITIETHOADONXUAT WHERE MAHDX = @MAHDX;

        -- Xóa hóa đơn xuất
        DELETE FROM HOADONXUAT WHERE MAHDX = @MAHDX;
END;
GO

--5: Cập nhật hóa đơn xuất và chi tiết hóa đơn xuất
GO
CREATE PROCEDURE NVKH_UpdateHoaDonXuat
    @MAHDX VARCHAR(10),
    @MANV VARCHAR(10),
    @MAKH VARCHAR(10),
    @NGAY DATE,
    @TONGTIEN DECIMAL(18, 0)
AS
BEGIN
    UPDATE HOADONXUAT
    SET MAKH = @MAKH, MANV = @MANV, TONGTIEN = @TONGTIEN, NGAY = @NGAY 
    WHERE MAHDX = @MAHDX;
END;
GO

CREATE PROCEDURE NVKH_UpdateCTHoaDonXuat
    @MAHDX VARCHAR(10),
    @MASANPHAM VARCHAR(10),
    @SOLUONG INT,
    @DONGIA DECIMAL(18, 0)
AS
BEGIN
    UPDATE CHITIETHOADONXUAT
    SET MASANPHAM = @MASANPHAM, SOLUONG = @SOLUONG, DONGIA = @DONGIA
    WHERE MAHDX = @MAHDX;
END;
GO

--6: Tìm kiếm hóa đơn xuất
GO
CREATE PROCEDURE NVKH_SearchHoaDonXuat
    @mahdx NVARCHAR(10)
AS
BEGIN
    SELECT HDX.MAHDX, NV.MANV, NV.TENNV, KH.MAKH, KH.TENKH, HDX.NGAY, HDX.TONGTIEN, 
           CTHDX.MASANPHAM, SP.TENSANPHAM, CTHDX.SOLUONG, CTHDX.DONGIA
    FROM HOADONXUAT HDX
    INNER JOIN NHANVIEN NV ON HDX.MANV = NV.MANV
    INNER JOIN KHACHHANG KH ON HDX.MAKH = KH.MAKH
    INNER JOIN CHITIETHOADONXUAT CTHDX ON HDX.MAHDX = CTHDX.MAHDX
    INNER JOIN SANPHAM SP ON CTHDX.MASANPHAM = SP.MASANPHAM
    WHERE HDX.MAHDX LIKE '%' + @mahdx + '%';
END;
GO

--7: Kiểm tra sự tồn tại của MAHDX trong bảng HOADONXUAT:
GO
CREATE PROCEDURE NVKH_CheckHoaDonXuatExistence
    @MAHDX NVARCHAR(10)
AS
BEGIN
    SELECT COUNT(*) AS CountResult FROM HOADONXUAT WHERE MAHDX = @MAHDX;
END;
GO

--8: Lấy đơn giá bán theo sản phẩm tương ứng
CREATE PROCEDURE NVKH_LayDonGiaBanTheoSP
    @MaSP  NVARCHAR(255)
AS
BEGIN
    SELECT DONGIABAN
    FROM SANPHAM 
    WHERE MASANPHAM = @MaSP
END;

